[pytest]
# 1. Default command line options
addopts = -v -s

# 2. Where to find tests
testpaths = tests

# 3. Suppress external library warnings
filterwarnings =
    ignore::DeprecationWarning
    ignore::UserWarning

# 4. Custom test markers (Tags)
markers =
    smoke: Run critical and basic tests to ensure core functionality is working
    regression: Run the comprehensive test suite to ensure nothing is broken
    negative: Run sad path and error handling scenarios